version: '3'

services:
  mongodb:
    restart: unless-stopped
    image: mongo:latest
    container_name: noodlapp-mongodb
    volumes:
      - mongodb-data:/data/noodlapp-db
    environment:
      MONGO_INITDB_ROOT_USERNAME: yourusername
      MONGO_INITDB_ROOT_PASSWORD: yourpassword
      MONGO_INITDB_DATABASE: noodlapp    
    networks:
      - dokploy-network

  cloudservice:
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile
    container_name: cloudservice
    environment:
      NODE_ENV: production
      PORT: 3000
      MASTER_KEY: mymasterkey
      APP_ID: myappid
      DATABASE_URI: mongodb://yourusername:yourpassword@noodlapp-mongodb:27017/noodlapp?authSource=admin
      PUBLIC_SERVER_URL: https://noodl.rsoft.ar/
    links:
      - mongodb
    networks:
      - dokploy-network

volumes:
  mongodb-data:
